//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace WPSoapRiaService.EmployeesService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="DomainServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPSoapRiaService.EmployeesService.QueryResultOfEmployee))]
    public partial class QueryResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int TotalCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResultOfEmployee", Namespace="DomainServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPSoapRiaService.EmployeesService.QueryResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPSoapRiaService.EmployeesService.DomainServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<WPSoapRiaService.EmployeesService.ValidationResultInfo>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPSoapRiaService.EmployeesService.ValidationResultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPSoapRiaService.EmployeesService.Employee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<WPSoapRiaService.EmployeesService.Employee>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<string>))]
    public partial class QueryResultOfEmployee : WPSoapRiaService.EmployeesService.QueryResult {
        
        private System.Collections.ObjectModel.ObservableCollection<object> IncludedResultsField;
        
        private System.Collections.ObjectModel.ObservableCollection<WPSoapRiaService.EmployeesService.Employee> RootResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<object> IncludedResults {
            get {
                return this.IncludedResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.IncludedResultsField, value) != true)) {
                    this.IncludedResultsField = value;
                    this.RaisePropertyChanged("IncludedResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<WPSoapRiaService.EmployeesService.Employee> RootResults {
            get {
                return this.RootResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.RootResultsField, value) != true)) {
                    this.RootResultsField = value;
                    this.RaisePropertyChanged("RootResults");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainServiceFault", Namespace="DomainServices")]
    public partial class DomainServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ErrorCodeField;
        
        private string ErrorMessageField;
        
        private bool IsDomainExceptionField;
        
        private System.Collections.ObjectModel.ObservableCollection<WPSoapRiaService.EmployeesService.ValidationResultInfo> OperationErrorsField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDomainException {
            get {
                return this.IsDomainExceptionField;
            }
            set {
                if ((this.IsDomainExceptionField.Equals(value) != true)) {
                    this.IsDomainExceptionField = value;
                    this.RaisePropertyChanged("IsDomainException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<WPSoapRiaService.EmployeesService.ValidationResultInfo> OperationErrors {
            get {
                return this.OperationErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationErrorsField, value) != true)) {
                    this.OperationErrorsField = value;
                    this.RaisePropertyChanged("OperationErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResultInfo", Namespace="DomainServices")]
    public partial class ValidationResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ErrorCodeField;
        
        private string MessageField;
        
        private System.Collections.ObjectModel.ObservableCollection<string> SourceMemberNamesField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<string> SourceMemberNames {
            get {
                return this.SourceMemberNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceMemberNamesField, value) != true)) {
                    this.SourceMemberNamesField = value;
                    this.RaisePropertyChanged("SourceMemberNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/SoapRiaService.Models")]
    public partial class Employee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CommentsField;
        
        private int IdField;
        
        private string LastNameField;
        
        private string NameField;
        
        private System.Nullable<int> SIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SID {
            get {
                return this.SIDField;
            }
            set {
                if ((this.SIDField.Equals(value) != true)) {
                    this.SIDField = value;
                    this.RaisePropertyChanged("SID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeesService.EmployeeDomainServiceSoap")]
    public interface EmployeeDomainServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/EmployeeDomainServiceSoap/GetEmployees", ReplyAction="http://tempuri.org/EmployeeDomainServiceSoap/GetEmployeesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WPSoapRiaService.EmployeesService.DomainServiceFault), Action="http://tempuri.org/EmployeeDomainServiceSoap/GetEmployeesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        System.IAsyncResult BeginGetEmployees(System.AsyncCallback callback, object asyncState);
        
        WPSoapRiaService.EmployeesService.QueryResultOfEmployee EndGetEmployees(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/EmployeeDomainServiceSoap/InsertEmployee", ReplyAction="http://tempuri.org/EmployeeDomainServiceSoap/InsertEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WPSoapRiaService.EmployeesService.DomainServiceFault), Action="http://tempuri.org/EmployeeDomainServiceSoap/InsertEmployeeDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        System.IAsyncResult BeginInsertEmployee(WPSoapRiaService.EmployeesService.Employee employee, System.AsyncCallback callback, object asyncState);
        
        void EndInsertEmployee(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/EmployeeDomainServiceSoap/UpdateEmployee", ReplyAction="http://tempuri.org/EmployeeDomainServiceSoap/UpdateEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WPSoapRiaService.EmployeesService.DomainServiceFault), Action="http://tempuri.org/EmployeeDomainServiceSoap/UpdateEmployeeDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        System.IAsyncResult BeginUpdateEmployee(WPSoapRiaService.EmployeesService.Employee currentEmployee, System.AsyncCallback callback, object asyncState);
        
        void EndUpdateEmployee(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/EmployeeDomainServiceSoap/DeleteEmployee", ReplyAction="http://tempuri.org/EmployeeDomainServiceSoap/DeleteEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WPSoapRiaService.EmployeesService.DomainServiceFault), Action="http://tempuri.org/EmployeeDomainServiceSoap/DeleteEmployeeDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        System.IAsyncResult BeginDeleteEmployee(WPSoapRiaService.EmployeesService.Employee employee, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteEmployee(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeDomainServiceSoapChannel : WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WPSoapRiaService.EmployeesService.QueryResultOfEmployee Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WPSoapRiaService.EmployeesService.QueryResultOfEmployee)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeDomainServiceSoapClient : System.ServiceModel.ClientBase<WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap>, WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap {
        
        private BeginOperationDelegate onBeginGetEmployeesDelegate;
        
        private EndOperationDelegate onEndGetEmployeesDelegate;
        
        private System.Threading.SendOrPostCallback onGetEmployeesCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertEmployeeDelegate;
        
        private EndOperationDelegate onEndInsertEmployeeDelegate;
        
        private System.Threading.SendOrPostCallback onInsertEmployeeCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateEmployeeDelegate;
        
        private EndOperationDelegate onEndUpdateEmployeeDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateEmployeeCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteEmployeeDelegate;
        
        private EndOperationDelegate onEndDeleteEmployeeDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteEmployeeCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public EmployeeDomainServiceSoapClient() {
        }
        
        public EmployeeDomainServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeDomainServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeDomainServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeDomainServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetEmployeesCompletedEventArgs> GetEmployeesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> InsertEmployeeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdateEmployeeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteEmployeeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap.BeginGetEmployees(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEmployees(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPSoapRiaService.EmployeesService.QueryResultOfEmployee WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap.EndGetEmployees(System.IAsyncResult result) {
            return base.Channel.EndGetEmployees(result);
        }
        
        private System.IAsyncResult OnBeginGetEmployees(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap)(this)).BeginGetEmployees(callback, asyncState);
        }
        
        private object[] OnEndGetEmployees(System.IAsyncResult result) {
            WPSoapRiaService.EmployeesService.QueryResultOfEmployee retVal = ((WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap)(this)).EndGetEmployees(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEmployeesCompleted(object state) {
            if ((this.GetEmployeesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEmployeesCompleted(this, new GetEmployeesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEmployeesAsync() {
            this.GetEmployeesAsync(null);
        }
        
        public void GetEmployeesAsync(object userState) {
            if ((this.onBeginGetEmployeesDelegate == null)) {
                this.onBeginGetEmployeesDelegate = new BeginOperationDelegate(this.OnBeginGetEmployees);
            }
            if ((this.onEndGetEmployeesDelegate == null)) {
                this.onEndGetEmployeesDelegate = new EndOperationDelegate(this.OnEndGetEmployees);
            }
            if ((this.onGetEmployeesCompletedDelegate == null)) {
                this.onGetEmployeesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEmployeesCompleted);
            }
            base.InvokeAsync(this.onBeginGetEmployeesDelegate, null, this.onEndGetEmployeesDelegate, this.onGetEmployeesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap.BeginInsertEmployee(WPSoapRiaService.EmployeesService.Employee employee, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertEmployee(employee, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap.EndInsertEmployee(System.IAsyncResult result) {
            base.Channel.EndInsertEmployee(result);
        }
        
        private System.IAsyncResult OnBeginInsertEmployee(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WPSoapRiaService.EmployeesService.Employee employee = ((WPSoapRiaService.EmployeesService.Employee)(inValues[0]));
            return ((WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap)(this)).BeginInsertEmployee(employee, callback, asyncState);
        }
        
        private object[] OnEndInsertEmployee(System.IAsyncResult result) {
            ((WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap)(this)).EndInsertEmployee(result);
            return null;
        }
        
        private void OnInsertEmployeeCompleted(object state) {
            if ((this.InsertEmployeeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertEmployeeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertEmployeeAsync(WPSoapRiaService.EmployeesService.Employee employee) {
            this.InsertEmployeeAsync(employee, null);
        }
        
        public void InsertEmployeeAsync(WPSoapRiaService.EmployeesService.Employee employee, object userState) {
            if ((this.onBeginInsertEmployeeDelegate == null)) {
                this.onBeginInsertEmployeeDelegate = new BeginOperationDelegate(this.OnBeginInsertEmployee);
            }
            if ((this.onEndInsertEmployeeDelegate == null)) {
                this.onEndInsertEmployeeDelegate = new EndOperationDelegate(this.OnEndInsertEmployee);
            }
            if ((this.onInsertEmployeeCompletedDelegate == null)) {
                this.onInsertEmployeeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertEmployeeCompleted);
            }
            base.InvokeAsync(this.onBeginInsertEmployeeDelegate, new object[] {
                        employee}, this.onEndInsertEmployeeDelegate, this.onInsertEmployeeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap.BeginUpdateEmployee(WPSoapRiaService.EmployeesService.Employee currentEmployee, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateEmployee(currentEmployee, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap.EndUpdateEmployee(System.IAsyncResult result) {
            base.Channel.EndUpdateEmployee(result);
        }
        
        private System.IAsyncResult OnBeginUpdateEmployee(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WPSoapRiaService.EmployeesService.Employee currentEmployee = ((WPSoapRiaService.EmployeesService.Employee)(inValues[0]));
            return ((WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap)(this)).BeginUpdateEmployee(currentEmployee, callback, asyncState);
        }
        
        private object[] OnEndUpdateEmployee(System.IAsyncResult result) {
            ((WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap)(this)).EndUpdateEmployee(result);
            return null;
        }
        
        private void OnUpdateEmployeeCompleted(object state) {
            if ((this.UpdateEmployeeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateEmployeeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateEmployeeAsync(WPSoapRiaService.EmployeesService.Employee currentEmployee) {
            this.UpdateEmployeeAsync(currentEmployee, null);
        }
        
        public void UpdateEmployeeAsync(WPSoapRiaService.EmployeesService.Employee currentEmployee, object userState) {
            if ((this.onBeginUpdateEmployeeDelegate == null)) {
                this.onBeginUpdateEmployeeDelegate = new BeginOperationDelegate(this.OnBeginUpdateEmployee);
            }
            if ((this.onEndUpdateEmployeeDelegate == null)) {
                this.onEndUpdateEmployeeDelegate = new EndOperationDelegate(this.OnEndUpdateEmployee);
            }
            if ((this.onUpdateEmployeeCompletedDelegate == null)) {
                this.onUpdateEmployeeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateEmployeeCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateEmployeeDelegate, new object[] {
                        currentEmployee}, this.onEndUpdateEmployeeDelegate, this.onUpdateEmployeeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap.BeginDeleteEmployee(WPSoapRiaService.EmployeesService.Employee employee, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteEmployee(employee, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap.EndDeleteEmployee(System.IAsyncResult result) {
            base.Channel.EndDeleteEmployee(result);
        }
        
        private System.IAsyncResult OnBeginDeleteEmployee(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WPSoapRiaService.EmployeesService.Employee employee = ((WPSoapRiaService.EmployeesService.Employee)(inValues[0]));
            return ((WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap)(this)).BeginDeleteEmployee(employee, callback, asyncState);
        }
        
        private object[] OnEndDeleteEmployee(System.IAsyncResult result) {
            ((WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap)(this)).EndDeleteEmployee(result);
            return null;
        }
        
        private void OnDeleteEmployeeCompleted(object state) {
            if ((this.DeleteEmployeeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteEmployeeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteEmployeeAsync(WPSoapRiaService.EmployeesService.Employee employee) {
            this.DeleteEmployeeAsync(employee, null);
        }
        
        public void DeleteEmployeeAsync(WPSoapRiaService.EmployeesService.Employee employee, object userState) {
            if ((this.onBeginDeleteEmployeeDelegate == null)) {
                this.onBeginDeleteEmployeeDelegate = new BeginOperationDelegate(this.OnBeginDeleteEmployee);
            }
            if ((this.onEndDeleteEmployeeDelegate == null)) {
                this.onEndDeleteEmployeeDelegate = new EndOperationDelegate(this.OnEndDeleteEmployee);
            }
            if ((this.onDeleteEmployeeCompletedDelegate == null)) {
                this.onDeleteEmployeeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteEmployeeCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteEmployeeDelegate, new object[] {
                        employee}, this.onEndDeleteEmployeeDelegate, this.onDeleteEmployeeCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap CreateChannel() {
            return new EmployeeDomainServiceSoapClientChannel(this);
        }
        
        private class EmployeeDomainServiceSoapClientChannel : ChannelBase<WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap>, WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap {
            
            public EmployeeDomainServiceSoapClientChannel(System.ServiceModel.ClientBase<WPSoapRiaService.EmployeesService.EmployeeDomainServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetEmployees(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetEmployees", _args, callback, asyncState);
                return _result;
            }
            
            public WPSoapRiaService.EmployeesService.QueryResultOfEmployee EndGetEmployees(System.IAsyncResult result) {
                object[] _args = new object[0];
                WPSoapRiaService.EmployeesService.QueryResultOfEmployee _result = ((WPSoapRiaService.EmployeesService.QueryResultOfEmployee)(base.EndInvoke("GetEmployees", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsertEmployee(WPSoapRiaService.EmployeesService.Employee employee, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = employee;
                System.IAsyncResult _result = base.BeginInvoke("InsertEmployee", _args, callback, asyncState);
                return _result;
            }
            
            public void EndInsertEmployee(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("InsertEmployee", _args, result);
            }
            
            public System.IAsyncResult BeginUpdateEmployee(WPSoapRiaService.EmployeesService.Employee currentEmployee, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = currentEmployee;
                System.IAsyncResult _result = base.BeginInvoke("UpdateEmployee", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUpdateEmployee(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("UpdateEmployee", _args, result);
            }
            
            public System.IAsyncResult BeginDeleteEmployee(WPSoapRiaService.EmployeesService.Employee employee, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = employee;
                System.IAsyncResult _result = base.BeginInvoke("DeleteEmployee", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeleteEmployee(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeleteEmployee", _args, result);
            }
        }
    }
}
